import "./globals.css";

import type { Metadata } from "next";

// import { Geist, Geist_Mono } from "next/font/google";

import { Toaster } from "../../components/ui/toaster";
import { Toaster as Sonner } from "../../components/ui/sonner";
import { SidebarProvider } from "../../components/ui/sidebar";
import SimpleHeader from "../../components/SimpleHeader";
import { AppSidebar } from "../../components/AppSidebar";


// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Toaster> */}
          {/* <Sonner> */}
            <SidebarProvider>
              <div className="min-h-screen flex w-full">
                <AppSidebar>
                  <div className="flex-1 flex flex-col">
                    <SimpleHeader>
                      <main className="flex-1">
                        {children}
                      </main>
                    </SimpleHeader>
                  </div>
              </AppSidebar>
              </div>
            </SidebarProvider>
          {/* </Sonner> */}
        {/* </Toaster> */}
      </body>
    </html>
  );
}
